### ISSUE TITLE
rename generated zip

### ISSUE THREAD

**Issue by brianleroux** [stevengill/coho#18]
should be phonegap-1.x.x.zip (not callback-phonegap-1.x.x.zip)

**Comment by stevengill** [comment]
The download on phonegap.com is coming from http://github.com/callback/phonegap. Coho generates a zip, but for now I am  just uploading the release directory to that repo. Once we have a place to upload these zips, this won't happen. When people download off of phonegap.com, they are downloading the zip generated off that repo and not the one in coho. Coho is generating phonegap-1.x.x.zip's.
